# Generated by Django 4.2.2 on 2025-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_entregador', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20)),
                ('data_contratacao', models.DateField()),
                ('num_entregas', models.PositiveIntegerField(default=0)),
                ('veiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('foto_entregador', models.ImageField(blank=True, null=True, upload_to='fotos_entregadores/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pedido', models.CharField(max_length=100)),
                ('tipo_massa', models.CharField(choices=[('Chocolate', 'Chocolate'), ('Amanteigada', 'Amanteigada'), ('Formigueiro', 'Formigueiro')], max_length=20)),
                ('recheio', models.CharField(choices=[('Brigadeiro', 'Brigadeiro'), ('Ninho', 'Ninho'), ('Prestígio', 'Prestígio'), ('Paçoca', 'Paçoca'), ('Frutas Vermelhas', 'Frutas Vermelhas')], max_length=20)),
                ('formato', models.CharField(max_length=50)),
                ('tamanho', models.CharField(choices=[('Mini', 'Mini (8 pessoas)'), ('PP', 'PP (15 pessoas)'), ('P', 'P (25 pessoas)'), ('M', 'M (45 pessoas)'), ('G', 'G (85 pessoas)')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_pedidos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField()),
                ('endereco_pedido', models.TextField(blank=True, null=True)),
                ('tipo_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Cartao', 'Cartão')], max_length=20)),
                ('status', models.CharField(choices=[('Aguardando Confirmação', 'Aguardando Confirmação'), ('Em producao', 'Em Produção'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Aguardando Confirmação', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
