# Generated by Django 5.2.6 on 2025-09-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vendedor', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pedido', models.CharField()),
                ('tipo_massa', models.CharField()),
                ('recheio', models.CharField()),
                ('formato', models.CharField()),
                ('tamanho', models.CharField()),
                ('andares', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_pedidos/')),
                ('observacoes', models.TextField(max_length=250)),
                ('data_entrega', models.DateTimeField()),
                ('endereco_pedido', models.TextField(max_length=100)),
                ('tipo_pagamento', models.CharField()),
                ('status', models.CharField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendadoce.cliente')),
            ],
        ),
    ]
