# Generated by Django 5.2.6 on 2025-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendadoce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Confirmação'), ('producao', 'Em Produção'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20),
        ),
    ]
