# Generated by Django 4.2.2 on 2025-11-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agendadoce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pedidos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="entregador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="agendadoce.entregador",
            ),
        ),
    ]
