# Generated by Django 5.2.6 on 2025-09-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendadoce', '0002_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='recheio',
            field=models.CharField(choices=[('Brigadeiro', 'Brigadeiro'), ('Ninho', 'Ninho'), ('Prestígio', 'Prestígio'), ('Paçoca', 'Paçoca'), ('Frutas Vermelhas', 'Frutas Vermelhas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Aguardando Confirmação', 'Aguardando Confirmação'), ('Em producao', 'Em Produção'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='aguardando', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tamanho',
            field=models.CharField(choices=[('Mini', 'Mini (8 pessoas)'), ('PP', 'PP (15 pessoas)'), ('P', 'P (25 pessoas)'), ('M', 'M (45 pessoas)'), ('G', 'G (85 pessoas)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_massa',
            field=models.CharField(choices=[('Chocolate', 'Chocolate'), ('Amanteigada', 'Amanteigada'), ('Formigueiro', 'Formigueiro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Cartao', 'Cartão')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
